# Generated by Django 4.1.2 on 2022-10-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockModel',
        ),
    ]
